url: https://sjbittner.github.io
baseurl:

# Site settings
title: Sara-Jane Bittner
email: sara-jane-Bittner@web.de
description: "I am a student of Cognitive Science, always motivated to search and find innovative concepts to work on!"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: linkedin.com/in/sara-jane-bittner/
  - title: github
    url: http://github.com/SJbittner

# Postal address (add as many lines as necessary)
address:
  - line: I DONT WANT YOU TO KNOW
  - line: I DONT WANT YOU TO KNOW

# Build settings
markdown: kramdown
permalink: pretty
